version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
      - "19093:19093"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:19093,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://kafka1:19093,OUTSIDE://kafka1:9093

  kafka2:
    image: wurstmeister/kafka:latest
    ports:
      - "9094:9094"
      - "19094:19094"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:19094,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka2:19094,OUTSIDE://kafka2:9094

  kafka3:
    image: wurstmeister/kafka:latest
    ports:
      - "9095:9095"
      - "19095:19095"
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:19095,OUTSIDE://localhost:9095
      KAFKA_LISTENERS: INSIDE://kafka3:19095,OUTSIDE://kafka3:9095
