version: "3.1"

services: 
  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - "8088:80"
      - "1882:1883"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx1/stream_conf.d/:/etc/nginx/stream_conf.d/
      - ./nginx1/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      app_net:
        ipv4_address: 172.16.238.16

  mqtt_broker:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
    - "18831:1883"
    networks:
      app_net:
        ipv4_address: 172.16.238.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
