version: "3.1"

services: 
  mqtt_broker:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile        
    restart: always
    ports:
      - 1882:1883
    volumes:
      - vernemqdata:/vernemq/data
      - vernemqlogs:/vernemq/logs
      - vernemqetc:/vernemq/etc

volumes: 
  vernemqdata:
  vernemqlogs:
  vernemqetc:
